### ISSUE TITLE
script can be killed

### ISSUE THREAD

**Issue by pipinoloco** [XiaoboHe/XTrader#15]
hello, i remember a few weeks ago i have installed this script and it wasn-t easy to kill but then you helped me to do so. I have installed in another server and when running with command python3 it can be killed with CTRL C. Please tell me how to run so it is not so easy to kill and it keeps running even after ending up my session on SSH.

**Comment by XiaoboHe** [comment]
# ubuntu
kill -9 $(ps -ef | grep xtrader.py | awk '{print $2}')

**Comment by pipinoloco** [comment]
and how to not kill it, i mean running on the vps server and to keep alive.
________________________________
De: XHE <notifications@github.com>
Enviado: domingo, 3 de junio de 2018 22:29
Para: XiaoboHe/XTrader
Cc: pipinoloco; Author
Asunto: Re: [XiaoboHe/XTrader] script can be killed (#15)

ubuntu

kill -9 $(ps -ef | grep xtrader.py | awk '{print $2}')

**Comment by XiaoboHe** [comment]
# running on daemon mode
nohup python3 xtrader.py &

# check process
ps -ef | grep xtrader
